fix: styling project management
kubeshop/monokle pull request #1111
Opened 2022-01-24 10:07 UTC by mortada-codes

This PR...

## Changes

- [x] Highlighted the active project in the table
- [x] Separated cluster management from project management  
- [x] project item hover color
- [ ] display confirm message when delete

## Fixes

-

## How to test it

-

## Screenshots

-

## Checklist

- [ ] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

2022-01-24 10:37 UTC, mortada-codes commented
@tommywhitehead  we have inconsistent colors between project dropdown and cluster dropdown! 
more context https://kubeshop.slack.com/archives/C023JNPUSP8/p1643011938397600

2022-01-25 10:50 UTC, topliceanurazvan requested changes
Left some comments, after fixing we can merge it! Great work! 👍🏻

2022-01-25 10:50 UTC, topliceanurazvan commented on src/index.css
> +  background: #111d2c;
Let's use the values from `Colors.ts`

2022-01-25 10:50 UTC, topliceanurazvan commented on src/index.css
> +  color: #13a8a8;
Same as above.

2022-01-25 10:50 UTC, topliceanurazvan commented on src/index.css
> +  border-left: 4px #13a8a8 solid;
Same as above.

2022-01-25 10:50 UTC, topliceanurazvan commented on src/index.css
> +  background: #111d2c;
Same as above.

2022-01-25 10:55 UTC, topliceanurazvan approved these changes

2022-01-25 10:59 UTC, merged