feat: edit toggle in cluster mode
kubeshop/monokle pull request #1648
Opened 2022-04-21 17:13 UTC by stan-gabriel

This PR...

## Changes
Add new Settings option: Allow editing resources

## How to test it
- 1 Go to Setting -> disable "Allow editing resources" under "Cluster Mode"
- 2 Enable "Cluster Mode"
- 3 Should not be able to edit resources

## Screenshots
![image](https://user-images.githubusercontent.com/12400110/164514011-25819457-0819-40eb-bfda-ff5fcc837877.png)

## Checklist

- [ ] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

2022-04-21 17:15 UTC, devcatalin requested changes

2022-04-21 17:15 UTC, devcatalin commented on src/components/molecules/Monaco/Monaco.tsx
> +    if (!settings.allowEditInClusterMode && previewType === 'cluster') {
```suggestion
    if (isInPreviewMode && previewType === 'cluster' && !settings.allowEditInClusterMode) {
```

2022-04-21 17:35 UTC, stan-gabriel commented on src/components/molecules/Monaco/Monaco.tsx
> +    if (!settings.allowEditInClusterMode && previewType === 'cluster') {
fixed

2022-04-21 18:33 UTC, olensmar commented
nice! would be great if we could fix #898 together with this - to be consistent with this added option

2022-04-25 17:53 UTC, stan-gabriel commented
> nice! would be great if we could fix #898 together with this - to be consistent with this added option
I will take a look and fix #898 as well

2022-04-26 13:43 UTC, devcatalin commented
Merging this now as I'd prefer having #898 in a separate PR

2022-04-26 13:43 UTC, merged