chore: add tabs
kubeshop/monokle pull request #1859
Opened 2022-05-29 16:49 UTC by erdkse

This PR...

## Changes

-

## Fixes

-

## How to test it

-

## Screenshots

-

## Checklist

- [ ] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

2022-05-29 21:49 UTC, erdkse commented on src/components/organisms/LazyDrawer/LazyDrawer.tsx
> +      headerStyle={{backgroundColor: '#293235'}}
Will ask @julioramosest about changing the panel header and body background colours. Because they look different in the design.

2022-05-31 06:55 UTC, topliceanurazvan requested changes
Can we rename the styling to the format we're now following `SettingsManager.styled.tsx` ?

2022-05-31 06:55 UTC, topliceanurazvan commented on src/components/organisms/SettingsManager/styled.tsx
> +export const Tabs = styled(RawTabs)``;
Maybe remove this if no styling is applied?

2022-05-31 09:09 UTC, topliceanurazvan approved these changes

2022-05-31 09:37 UTC, merged