enhancement : Disable Deploy, Cluster Compare, Diff actions if cluster is no…
kubeshop/monokle pull request #2051
Opened 2022-07-05 14:11 UTC by sriniva7

This PR...

## How to test it

- Change the cluster configure in settings

## Screenshots

Below image show button are enabled when the cluster is available.
![image](https://user-images.githubusercontent.com/35147480/177345576-610892ec-3910-4d4f-b538-45dd6f6f0ea5.png)

Below image show button are disabled when the cluster is available.
![image](https://user-images.githubusercontent.com/35147480/177346005-cf54b87c-eacb-42ab-bf14-1cac0c54ffbb.png)

## Checklist

- [x] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

2022-07-06 06:25 UTC, topliceanurazvan requested changes
I wouldn't disable the Compare button anymore as right now we are also allowing the user to compare local resources with helm/kustomize preview. Instead I would just disable the `Cluster` option from the dropdown ( screenshot ):

![image](https://user-images.githubusercontent.com/47887589/177482760-58462d90-9d3c-4ca1-973c-7f31fd8a9281.png)

Also we are having hotkeys for quickly deploying and diffing, we should not allow the user to use them if the kubeconfig is not valid.

![image](https://user-images.githubusercontent.com/47887589/177483172-750603e2-881e-4658-9cf2-b00f6f7a7e54.png)


As another suggestions, when `Deploy/Diff` are disable, maybe we should show the tooltip with a different message like: `Your kubeconfig is not valid !`

2022-07-06 06:25 UTC, topliceanurazvan commented on src/components/organisms/NavigatorPane/CompareButton.tsx
> +  const isCompareDisabled = () => {
Here you could use `useMemo` instead, without needing a useEffect

2022-07-06 14:14 UTC, sriniva7 commented
> Great work so far 👍🏻 the only thing remaining is to not let the user use hotkeys. We can find it in `HotKeysHandler` component - do the action for `DIFF_RESOURCE` and `APPLY_SELECTION` only if the kubeconfig path is valid

Okay I will do that

2022-07-08 07:38 UTC, topliceanurazvan requested changes

2022-07-08 07:38 UTC, topliceanurazvan commented on src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
> +      if (!isKubeConfigPathValid) return;
```suggestion
      if (!isKubeConfigPathValid) {
        return;
      }

```

2022-07-08 07:38 UTC, topliceanurazvan commented on src/components/organisms/HotKeysHandler/HotKeysHandler.tsx
> +      if (!isKubeConfigPathValid) return;
```suggestion
      if (!isKubeConfigPathValid) {
        return;
      }

```

2022-07-08 07:38 UTC, topliceanurazvan commented on electron/app/menu.ts
> +  const isKubeConfigPathValid = useAppSelector(kubeConfigPathValidSelector);
```suggestion
  const isKubeConfigPathValid = kubeConfigPathValidSelector(state);
```

2022-07-08 07:38 UTC, topliceanurazvan commented on electron/app/menu.ts
>          enabled: Boolean(state.main.selectedResourceId),
```suggestion
        enabled: Boolean(state.main.selectedResourceId) && Boolean(isKubeConfigPathValid),
```

We could just use the enabled property for making the option disabled if the kubeConfig path is not valid

2022-07-08 07:38 UTC, topliceanurazvan commented on electron/app/menu.ts
> +          if(!isKubeConfigPathValid)return;
```suggestion
```

2022-07-08 07:38 UTC, topliceanurazvan commented on electron/app/menu.ts
> +
```suggestion
```

2022-07-08 07:38 UTC, topliceanurazvan commented on electron/app/menu.ts
> +          if(!isKubeConfigPathValid)return;
```suggestion
```

2022-07-08 07:38 UTC, topliceanurazvan commented on electron/app/menu.ts
>          enabled: Boolean(state.main.selectedResourceId),
```suggestion
        enabled: Boolean(state.main.selectedResourceId) && Boolean(isKubeConfigPathValid),
```

Same as above

2022-07-08 07:38 UTC, topliceanurazvan commented on electron/app/menu.ts
> +import {useAppSelector} from '@redux/hooks';
```suggestion
```

2022-07-08 07:38 UTC, topliceanurazvan commented
Looks good 👍🏻 - left a couple of suggestions

2022-07-08 08:17 UTC, topliceanurazvan approved these changes
Great work @sriniva7 ! Thank you for your contribution 🙌🏻

2022-07-08 09:20 UTC, merged