fix: update file content for Monaco editor when deleting its resource
kubeshop/monokle pull request #2072
Opened 2022-07-10 19:47 UTC by jmelnych

This PR...

## Changes

-

## Fixes
update file content for Monaco editor when deleting its resource
-

## How to test it

-

## Screenshots

-

## Checklist

- [ ] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

2022-07-10 19:56 UTC, erdkse approved these changes
LGTM!

2022-07-11 06:18 UTC, topliceanurazvan requested changes
LGTM! 👍🏻 Lets do it also for the multiple resource delete

2022-07-11 12:47 UTC, devcatalin approved these changes

2022-07-11 12:48 UTC, topliceanurazvan approved these changes

2022-07-11 12:51 UTC, merged