Julia/feat/code form editor
kubeshop/monokle pull request #2329
Opened 2022-09-09 09:23 UTC by jmelnych

This PR...

## Changes

-

## Fixes

-

## How to test it

-

## Screenshots

-

## Checklist

- [ ] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

2022-09-12 10:42 UTC, devcatalin commented
<img width="828" alt="image" src="https://user-images.githubusercontent.com/20538711/189634366-b13562f1-065b-4134-a70d-1b6149b83155.png">

I'm getting an error when I select the `Form` tab on a resource

2022-09-14 08:09 UTC, topliceanurazvan requested changes
Code looks good, great work 🙌🏻  Found just a little styling problem with some missing padding.

![image](https://user-images.githubusercontent.com/47887589/190097933-10f31905-7d0c-4222-b35d-4c1b7b61a45d.png)

Also I'm thinking if we should not have all the levels directly expanded as it hits the performance a little bit on rendering all of them - for big forms especially - wdyt? @jmelnych @devcatalin

2022-09-19 09:41 UTC, topliceanurazvan requested changes
We should have same px for both left and right paddings ( 10px )

![image](https://user-images.githubusercontent.com/47887589/190990693-06cf73a0-3ac7-4e5e-a3a5-6ea4e4f9446c.png)

![image](https://user-images.githubusercontent.com/47887589/190990731-539cd14d-db82-4615-b5c5-988216f07be1.png)

2022-09-19 16:16 UTC, topliceanurazvan approved these changes

2022-09-20 07:34 UTC, merged