fix:   maximum hook update
kubeshop/monokle pull request #3144
Opened 2023-02-10 12:06 UTC by mortada-codes

This PR...

## Changes

-

## Fixes

-

## How to test it

-

## Screenshots

-

## Checklist

- [ ] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

2023-02-10 16:53 UTC, devcatalin commented
I've made some changes thinking that this might fix the FormEditor but it looks like the Form is still infintely re-rendering for some reason. We'll have to test it more.

2023-02-13 07:58 UTC, mortada-codes commented
> I've made some changes thinking that this might fix the FormEditor but it looks like the Form is still infintely re-rendering for some reason. We'll have to test it more.

working on it

2023-02-13 15:19 UTC, devcatalin requested changes

2023-02-13 15:19 UTC, devcatalin commented on src/components/molecules/FormEditor/FormEditor.tsx
> +  useWhatChanged([fileMap, selectedFilePath, selectedResource, formData]);
Let's remove this now since it was only used for debugging!

2023-02-13 15:21 UTC, devcatalin requested changes

2023-02-13 15:21 UTC, devcatalin commented on src/redux/thunks/saveResourceChanges.ts
> +export const saveResourceChanges = createAsyncThunk<void, string, {dispatch: AppDispatch; state: RootState}>(
Let's rename this to `saveFormEditorResource` so we don't confuse it with something else

2023-02-13 15:21 UTC, devcatalin commented on src/redux/thunks/readResourceFile.ts
> +export const readResourceFile = createAsyncThunk<string | undefined, string, {dispatch: AppDispatch; state: RootState}>(
We can rename this to `readFileThunk` since it only reads a file

2023-02-13 15:27 UTC, devcatalin approved these changes

2023-02-13 15:28 UTC, merged