fix: reload kubeConfig when changing config path
kubeshop/monokle pull request #3284
Opened 2023-02-21 08:31 UTC by mortada-codes

This PR...

## Changes

-

## Fixes

-

## How to test it

-

## Screenshots

-

## Checklist

- [ ] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

2023-02-21 09:00 UTC, topliceanurazvan requested changes

2023-02-21 09:04 UTC, mortada-codes commented on src/components/organisms_new/ExplorerPane/FilePane/FileSystemTree/TreeNode/hooks.tsx
>  import {useResourceMetaMapRef} from '@redux/selectors/resourceMapSelectors';
removed

2023-02-21 09:04 UTC, topliceanurazvan submitted a review, later dismissed

2023-02-22 12:23 UTC, topliceanurazvan approved these changes

2023-02-22 12:24 UTC, merged