feat: compare single file
kubeshop/monokle pull request #3354
Opened 2023-03-07 14:55 UTC by topliceanurazvan

This PR...

## Changes

-

## Fixes

-

## How to test it

-

## Screenshots

-

## Checklist

- [ ] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

2023-03-07 14:57 UTC, erdkse submitted a review, later dismissed
lgtm

2023-03-07 15:18 UTC, devcatalin requested changes

2023-03-07 15:18 UTC, devcatalin commented on src/components/organisms/FileCompareModal/FileCompareModal.tsx
> +  const fileMap = useAppSelector(state => state.main.fileMap);
`fileMap` is only used to check if a file exists, so we should make it a ref as we don't want the component to re-render when any other file changes:

```ts
const fileMapRef = useRefSelector(state => state.main.fileMap);
```

2023-03-07 15:18 UTC, devcatalin commented on src/components/organisms/FileCompareModal/FileCompareModal.tsx
> +  const rootFilePath = useMemo(() => fileMap[ROOT_FILE_ENTRY].filePath, [fileMap]);
we have a `rootFilePathSelector` for this

2023-03-07 15:18 UTC, devcatalin commented on src/components/organisms/FileCompareModal/FileCompareModal.tsx
> +    setCurrentFileCode(fs.readFileSync(absoluteFilePath, 'utf-8'));
since this is a `useEffect` and not just a `useMemo` , we should make this operation async

2023-03-08 12:25 UTC, devcatalin submitted a review, later dismissed

2023-03-08 12:30 UTC, devcatalin approved these changes

2023-03-08 12:31 UTC, merged