Editor placeholder update
kubeshop/monokle pull request #3362
Opened 2023-03-08 14:29 UTC by KarthikRaju391

This PR...

## Changes

- Changed the image and the links in editor placeholder based on the design provided

## Screenshots

![image](https://user-images.githubusercontent.com/67912316/223738944-0c69b4ee-fe50-41cd-a877-4578b6dc5cc6.png)

## Checklist

- [x] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

2023-03-09 08:59 UTC, topliceanurazvan requested changes
Looking good, nice work! 🙌🏻  I've left a couple of comments

2023-03-09 08:59 UTC, topliceanurazvan commented on src/components/molecules/MonacoPlaceholder/MonacoPlaceholder.tsx
> +          <S.InfoLink href="https://chrome.google.com/webstore/detail/monokle-cloud-chrome-exte/loojojkleiolidaodalflgbmaijeibob?hl=en">
Here we need to use `shell.openExternal(link)`, so that the link is opened in your browser, not on the monokle app itself

2023-03-09 08:59 UTC, topliceanurazvan commented on src/components/molecules/MonacoPlaceholder/MonacoPlaceholder.tsx
> +          <S.InfoLink href="https://monokle.io/download">Get the CLI</S.InfoLink>
Same as above, use `shell.openExternal(https://monokle.io/download)`

2023-03-09 08:59 UTC, topliceanurazvan commented on src/components/molecules/MonacoPlaceholder/MonacoPlaceholder.styled.tsx
> +  opacity: 0.7;
No need for opacity in here

2023-03-09 08:59 UTC, topliceanurazvan commented on src/components/molecules/MonacoPlaceholder/MonacoPlaceholder.styled.tsx
> +    opacity: 1;
We can remove the opacity

2023-03-09 08:59 UTC, topliceanurazvan commented on src/components/molecules/MonacoPlaceholder/MonacoPlaceholder.styled.tsx
>      color: ${Colors.grey7};
Color should be `grey9` on hover

2023-03-09 08:59 UTC, topliceanurazvan commented on src/components/molecules/MonacoPlaceholder/MonacoPlaceholder.tsx
> +        <S.Text>Everything about your Cluster live</S.Text>
This one should also be a `InfoLink` and should lead you to the dashboard option from the left menu

2023-03-09 09:09 UTC, KarthikRaju391 commented
Will make the necessary changes @topliceanurazvan

2023-03-09 18:23 UTC, KarthikRaju391 commented
Hey @topliceanurazvan, I made the requested changes. Little heads up, I forgot to sync my fork with the latest changes before committing my changes so I pushed another commit with the synced changes.

2023-03-10 09:41 UTC, topliceanurazvan approved these changes
Great work! 🙌🏻 Thank you for contributing to Monokle

2023-03-10 09:42 UTC, merged