fix: stay selected left menu when cluster namespace changed
kubeshop/monokle pull request #3673
Opened 2023-04-09 22:22 UTC by erdkse

This PR...

## Changes

-

## Fixes

-

## How to test it

-

## Screenshots

-

## Checklist

- [ ] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

2023-04-09 22:28 UTC, erdkse commented
- also fixes Dashboard Pane filter, Couldn't find an issue for it

2023-04-10 03:30 UTC, erdkse commented
https://user-images.githubusercontent.com/2957624/230819988-78357663-2c14-49ee-8378-eaa86da5519c.mov

2023-04-10 07:25 UTC, topliceanurazvan requested changes

2023-04-10 07:25 UTC, topliceanurazvan commented on src/components/organisms/DashboardPane/DashboardPane.tsx
> +          .filter(p => p.level === level)
Can we do just one single filtering in here so we don't iterate twice the same array?

2023-04-10 07:27 UTC, topliceanurazvan commented
Also as a nice have we could add a skeleton loading in the list of items while the namespace is being changed

2023-04-10 09:05 UTC, topliceanurazvan approved these changes

2023-04-10 09:15 UTC, merged