chore: add styles for exluded folders
kubeshop/monokle pull request #3680
Opened 2023-04-10 03:10 UTC by erdkse

This PR...

## Changes

-

## Fixes

-

## How to test it

-

## Screenshots

-

## Checklist

- [ ] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

2023-04-10 03:14 UTC, erdkse commented
https://user-images.githubusercontent.com/2957624/230818115-d5a6348d-8778-4d41-8208-031273cb7e34.mov


I am not sure what should be the desired behavior of excluded files/folders.

2023-04-10 09:25 UTC, olensmar commented
hm... I think there are several states for a file/folder:
- included - containing supported content: regular white
- included - containing unsupported content: greyed out  (for a folder this is only true if all its contents are also unsupported)
- excluded from parsing: - greyed out + italic?
- filtered out - with supported content: ?
- filtered out - with unsupported content: ? 

@julioramosest should the last two be simply greyed out? or some other style?

2023-04-10 10:19 UTC, julioramosest commented
@olensmar @erdkse right, let's use 1 single style for excluded folders, which is greyed out (same grey as currently for already dimmed files).
- We can use italic for excluded from parsing
- We can add a tooltip to give details on the exluding type/reason

2023-04-14 10:53 UTC, olensmar commented
@erdkse can we finish this so we can add support for excluded folders in #3715 ?

2023-04-18 10:27 UTC, erdkse commented
@olensmar I had to fix https://github.com/kubeshop/monokle/issues/3717 and https://github.com/kubeshop/monokle/issues/3715 while fixing this issue,

all completed right now. @topliceanurazvan should approve.

2023-04-19 07:47 UTC, topliceanurazvan requested changes

2023-04-19 07:47 UTC, topliceanurazvan commented on src/components/organisms/ExplorerPane/FilePane/FileSystemTree/FileSystemTree.tsx
> +  const [fileMap, fileMapRef] = useSelectorWithRef(state => state.main.fileMap);
`fileMap` is not used here so we can directly go for `const fileMapRef` = useRefSelector(...)

2023-04-19 07:47 UTC, topliceanurazvan commented on src/components/organisms/ExplorerPane/FilePane/FileSystemTree/FileSystemTree.tsx
> +    console.log('fileMapRef', fileMapRef);
Do we need this?

2023-04-19 07:47 UTC, topliceanurazvan commented on src/components/organisms/ExplorerPane/FilePane/FileSystemTree/TreeNode/TreeNodeFolder.tsx
> +  const isExcluded = useIsExcluded(folderEntry);
is this needed?

2023-04-19 07:47 UTC, topliceanurazvan commented on src/components/organisms/ExplorerPane/FilePane/FileSystemTree/TreeNode/hooks.tsx
> +export const useIsExcluded = (fileEntry?: FileEntry) => {
Can we use directly `fileEntry.isExcluded` instead of creating a hook?

2023-04-19 07:51 UTC, topliceanurazvan commented
Should we maybe disable all the actions from here ( except for `remove from exclude`, `copy path` and `reveal in explorer` ) while the file is excluded?

![image](https://user-images.githubusercontent.com/47887589/233006368-95426ced-51d3-4799-b065-6a9735aee96a.png)

2023-04-19 07:52 UTC, topliceanurazvan commented
Also creating a new file in the excluded folder doesn't mark it as excluded too...

![image](https://user-images.githubusercontent.com/47887589/233006566-09c28ac4-220a-4702-983a-3c23a96e3f82.png)

2023-04-19 07:54 UTC, olensmar commented
good finds @topliceanurazvan - i suggest we disable the following actions:
- duplicate
- compare with another file
- rename
- delete

the others might still make sense!? @julioramosest ?

2023-04-19 08:11 UTC, topliceanurazvan commented
Also I can still select this not supported files

![image](https://user-images.githubusercontent.com/47887589/233006979-5fcecd22-8849-407c-9e14-cff8b3ae2aad.png)

2023-04-19 08:39 UTC, julioramosest commented
@olensmar @topliceanurazvan for an excluded file, first submenu action (3 dots) should be "Remove from excluded". If there are other actions than can be performed, yes, just keep them in. If no actions are going to be provided for a certain dimmed file (we are just illustrating the file), then:
- Hover effect can be kept
- 3 dots menu on the right should not appear

2023-04-20 07:25 UTC, topliceanurazvan commented
![image](https://user-images.githubusercontent.com/47887589/233291558-5a70a7aa-5737-4b2d-9821-a44cd21b1537.png)

Seems like the dots menu is not shown at all anymore

2023-04-20 09:46 UTC, erdkse commented
3 dots menu is not visible only for unsupported files, it is visible for excluded files @topliceanurazvan

2023-05-02 14:55 UTC, closed without merging