fix: reset validation count when switching projects
kubeshop/monokle pull request #3853
Opened 2023-05-03 11:30 UTC by mortada-codes

This PR...

## Changes

-  reset validation count when switching projects

## Fixes

-

## How to test it

-

## Screenshots

-

## Checklist

- [ ] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

2023-05-03 11:33 UTC, olensmar commented on src/redux/validation/validation.slice.ts
> +      state.lastResponse = undefined;
what if the `setRootFolder` action fails? will we end up with the previous project with no `lastResponse`? or no project at all?

2023-05-03 13:52 UTC, topliceanurazvan requested changes

2023-05-04 06:47 UTC, mortada-codes commented on src/redux/validation/validation.slice.ts
> +      state.lastResponse = undefined;
When `setRootFolder.rejected`, we keep exists folder opened. as in the video 


https://user-images.githubusercontent.com/20525304/236129635-30a1c9bc-b53b-4779-9da0-9b70952c99d9.mp4

2023-05-04 10:01 UTC, topliceanurazvan approved these changes

2023-05-04 10:03 UTC, merged