refactor: use new editor in cluster dashboard
kubeshop/monokle pull request #3882
Opened 2023-05-05 12:30 UTC by devcatalin

This PR...

## Changes

- made the new editor work in the cluster dashboard

2023-05-08 07:55 UTC, olensmar approved these changes
LGTM..

2023-05-09 07:09 UTC, topliceanurazvan requested changes

2023-05-09 07:09 UTC, topliceanurazvan commented on src/components/organisms/ActionsPane/ActionsPane.tsx
>          ),
Can we remove unnecessary dependencies at line `388`

2023-05-09 07:09 UTC, topliceanurazvan commented on src/editor/listeners/editorSelection.listener.ts
> +        console.log({resourceIdentifier});
Lets remove this

2023-05-09 13:41 UTC, merged