feat : hotkey navigation popup
kubeshop/monokle pull request #961
Opened 2022-01-07 10:18 UTC by topliceanurazvan

This PR creates a quick search popup for applying `kind` or `namespace` filter, or select a resource.

## Changes

- `CTRL/CMD Shift P` hotkey to open the quick search
- Updated docs with missing hotkeys

## Fixes

- `ScrollIntoView` not getting the element into view in some cases.

## Checklist

- [ ] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

2022-01-07 12:55 UTC, olensmar commented
this is great @topliceanurazvan - i'm wondering if in the situation below we could have some way to set "argo" as the name filter in the filter panel!? perhaps a "Filter all" link/button next to the "Resources" label!? @tommywhitehead could that work?

![image](https://user-images.githubusercontent.com/1917063/148546704-a759948f-9963-403a-8b0f-ce89776bdd6c.png)

2022-01-07 13:03 UTC, devcatalin commented
@olensmar I think it should be a separate option in the dropdown so it can be selected with arrow keys.

Maybe we should have a group named "Actions" where we add that option, or it could be the first option under Resources..

2022-01-09 07:16 UTC, olensmar commented
good idea @devcatalin - perhaps we do this in a separate PR so we get this one merged?

2022-01-09 07:21 UTC, olensmar reviewed
lgtm - the only thing I've noticed is that when pressing arrow-up to get to the last entry in the filtered list, and then pressing arrow-down to get back to the first entry, the label above the first entry is scrolled out of view: 

![image](https://user-images.githubusercontent.com/1917063/148673121-f5f5e309-46f1-4319-b276-7b0ef5606004.png)

pressing arrow-up + arrow-down results in 

![image](https://user-images.githubusercontent.com/1917063/148673131-5206cdb0-9851-4312-b09f-640267dc59b5.png)

2022-01-10 10:40 UTC, DmitryEremenko requested changes

2022-01-10 10:40 UTC, DmitryEremenko commented on src/components/molecules/ScrollIntoView/ScrollIntoView.tsx
> +        // containerRef.current?.scrollIntoView({behavior: 'smooth', block: 'center', inline: 'nearest'});
Do we need this commented out line? If not let's delete it

2022-01-10 11:01 UTC, olensmar approved these changes
great!

2022-01-10 11:23 UTC, DmitryEremenko approved these changes

2022-01-10 11:23 UTC, merged